server {
    listen 9000;
    root /usr/share/nginx/html;
    index index.html;

    add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
    add_header Pragma "no-cache";
    add_header Expires "0";

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(html)$ {
        add_header Cache-Control "no-store, no-cache, must-revalidate";
        expires -1;
    }
}
